### ISSUE TITLE
Install Step by Step

### ISSUE THREAD

**Issue by Panchitor** [mbakholdina/srt-stats-plotting#3]
Hi, can you tell me how to install it?

I have phyton and intstale dsd installed
Then, when running the command, this error indicates to me:

: ~ / srt-stats-plotting $ sudo python3 plot_srt_stats.py --is-sender /home/pi/Desktop/stats-rcv-lat0.csv
   File "plot_srt_stats.py", line 162
     print (f'fec_overhead: {sum_overhead}% ')
                                           ^
SyntaxError: invalid syntax
can you help me?
Thank you.

**Comment by mbakholdina** [comment]
This problem is related to [the f-strings interpolation](https://stackoverflow.com/questions/42126794/python-3-returns-invalid-syntax-when-trying-to-perform-string-interpolation) which was added in Python 3.6. Please check the python version you are currently using and update it to 3.6 or higher if needed.

**Comment by Panchitor** [comment]
Install python version 7 and I still have the same problem.
copy python verification and error running.
pi@raspberrypi:~/srt/srt-stats-plotting $ sudo python3.7 plot_srt_stats.py --is-sender /home/pi/Desktop/stats-rcv-lat0.csv
Traceback (most recent call last):
  File "plot_srt_stats.py", line 5, in <module>
    import bokeh.io
ModuleNotFoundError: No module named 'bokeh'
pi@raspberrypi:~/srt/srt-stats-plotting $ python3.7 -V
Python 3.7.0
